AstonRoseFrondEnd/Models/Property/Property.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using AstonRoseFrondEnd.Models;

namespace AstonRoseFrondEnd.Models
{
    public class Property
    {
        public Property()
        {
            AvailableType = new List<SelectListItem>();
            AvailableSize = new List<SelectListItem>();
            AvailableTenure = new List<SelectListItem>();
            AvailableStatus = new List<SelectListItem>();
            AvailableRegion = new List<SelectListItem>();
            AvailableCategories = new List<SelectListItem>();
        }

        [Key]
        public int Id { get; set; }

        //[Required(ErrorMessage = "Category is Required")]
        [Display(Name = "Category")]
        public string Category { get; set; }

        //[Required(ErrorMessage = "Type is Required")]
        [Display(Name = "Type")]
        public string Type { get; set; }
        [NotMapped]
        public IList<SelectListItem> AvailableType { get; set; }

        //[Required(ErrorMessage = "Size is Required")]
        [Display(Name = "Size")]
        public string Size { get; set; }


        [Display(Name = "Actual Floor Area (sq ft)")]
        public string SquareFeet { get; set; }


        [Display(Name = "Actual Floor Area (sq m)")]
        public string SquareMeters { get; set; }

        [NotMapped]
        public IList<SelectListItem> AvailableSize { get; set; }

        [NotMapped]
        public IList<SelectListItem> AvailableCategories { get; set; }

        //[Required(ErrorMessage = "Tenure is Required")]
        [Display(Name = "Tenure")]
        public string Tenure { get; set; }
        [NotMapped]
        public IList<SelectListItem> AvailableTenure { get; set; }

        //[Required(ErrorMessage = "Status is Required")]
        [Display(Name = "Status")]
        public string Status { get; set; }
        [NotMapped]
        public IList<SelectListItem> AvailableStatus { get; set; }

        //[Required(ErrorMessage = "Region is Required")]
        [Display(Name = "Region")]
        public string Region { get; set; }
        [NotMapped]
        public IList<SelectListItem> AvailableRegion { get; set; }

        //[Required(ErrorMessage = "Price is Required")]
        [Display(Name = "Price")]
        public string Price { get; set; }

        //[Required(ErrorMessage = "PriceFlag is Required")]
        [Display(Name = "PriceFlag")]
        public string PriceFlag { get; set; }


        ////[Required(ErrorMessage = "Image is Required")]
        [Display(Name = "Image")]
        public string Image { get; set; }

        ////[Required(ErrorMessage = "Video is Required")]
        [Display(Name = "Video")]
        public string Video { get; set; }

        //[Required(ErrorMessage = "BuildingName is Required")]
        [Display(Name = "Building Name")]
        public string BuildingName { get; set; }

        //[Required(ErrorMessage = "Address1 is Required")]
        [Display(Name = "Address1")]
        public string Address1 { get; set; }

        ////[Required(ErrorMessage = "Address2 is Required")]
        [Display(Name = "Address2")]
        public string Address2 { get; set; }

        ////[Required(ErrorMessage = "Address3 is Required")]
        [Display(Name = "Address3")]
        public string Address3 { get; set; }

        //[Required(ErrorMessage = "Town is Required")]
        [Display(Name = "Town")]
        public string Town { get; set; }

        //[Required(ErrorMessage = "County is Required")]
        [Display(Name = "County")]
        public string County { get; set; }

        //[Required(ErrorMessage = "Postcode is Required")]
        [Display(Name = "Postcode")]
        public string Postcode { get; set; }

        //[Required(ErrorMessage = "Description is Required")]
        [Display(Name = "Description")]
        [AllowHtml]
        public string Description { get; set; }

        ////[Required(ErrorMessage = "PDF is Required")]
        [Display(Name = "PDF")]
        public string PDF { get; set; }

        ////[Required(ErrorMessage = "EPC is Required")]
        [Display(Name = "EPC")]
        public string EPC { get; set; }
        [Display(Name = "Incentive")]
        public string Incentive { get; set; }

        ////[Required(ErrorMessage = "ContactIDs is Required")]
        [Display(Name = "Contacts")]
        public string ContactIDs { get; set; }

        ////[Required(ErrorMessage = "Date Created is Required")]
        [Display(Name = "Date Created")]
        public DateTime DateCreated { get; set; }

        [NotMapped]
        public List<Team> PropertyContactList { get; set; }

        [NotMapped]
        public List<string> PropertyContactSelectedIdList { get; set; }

        public double? Longitude { get; set; }
        public double? Latitude { get; set; }
        public string GoogleMapURL { get; set; }


        [Display(Name = "Meta Title")]
        public string MetaTitle { get; set; }

        [Display(Name = "Meta Description")]
        public string MetaDescription { get; set; }
        [NotMapped]
        public bool Added { get; set; }
        public override string ToString()
        {
            string returnVal = "";
            returnVal += (string.IsNullOrEmpty(BuildingName) ? "" : BuildingName + ", ");

            if (Address1 != null && !returnVal.Contains(Address1))
                returnVal += (string.IsNullOrEmpty(Address1) ? "" : Address1 + ", ");
            if (Address2 != null && !returnVal.Contains(Address2))
                returnVal += (string.IsNullOrEmpty(Address2) ? "" : Address2 + ", ");
            if (Address3 != null && !returnVal.Contains(Address3))
                returnVal += (string.IsNullOrEmpty(Address3) ? "" : Address3 + ", ");
            if (Town != null && !returnVal.Contains(Town))
                returnVal += (string.IsNullOrEmpty(Town) ? "" : Town + ", ");
            if (County != null && !returnVal.Contains(County))
                returnVal += (string.IsNullOrEmpty(County) ? "" : County + ", ");

            if (returnVal.EndsWith(", "))
                returnVal = returnVal.Remove(returnVal.LastIndexOf(", "));

            if (Postcode != null && !returnVal.Contains(Postcode))
                returnVal += (string.IsNullOrEmpty(Postcode) ? "" : " " + Postcode );

            return returnVal;
        }
    }

    public class AutoSuggestion
    {
        [Key]
        public string Place { get; set; }
    }

    public class MyProperty
    {
        public List<Property> MyProperties { get; set; }
        public EnquiryUser Enquiry { get; set; }
        public Pagination Pagination { get; set; }
    }
    public class Map
    {
        public string MapPoints { get; set; }
    }
}

AstonRoseFrondEnd/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AstonRoseFrondEnd.Controllers;
using AstonRoseFrondEnd.Models;
using System.Data.SqlClient;
using AstonRoseFrondEnd.Models;
using System.Text;
using System.Net.Mail;
using System.Configuration;
using AstonRoseFrondEnd.Helpers;
using SolrNet;
using SolrNet.DSL;
using SolrNet.Commands.Parameters;
using SolrNet.Exceptions;
using System.Globalization;
using System.Text.RegularExpressions;

namespace AstonRoseFrondEnd.Controllers
{
    public class PropertyController : BaseController
    {
        //private AstonRoseCMSContext db = new AstonRoseCMSContext();
        private readonly ISolrReadOnlyOperations<SolrProperty> solr;

        public PropertyController(ISolrReadOnlyOperations<SolrProperty> solr)
        {
            this.solr = solr;

        }
        public ActionResult Search()
        {
            return View();
        }


        public ActionResult Index()
        {
            ViewBag.MetaTitle = "Property Search : Aston Rose";
            ViewBag.MetaDescription = "Property Search : Aston Rose";
            ViewBag.PageTitle = "Property Search  - ";
            PropertyFilter propertyFilter = new PropertyFilter();
            SplitValues(propertyFilter);
            return View(propertyFilter);
        }

        private void SplitValues(PropertyFilter propertyFilter)
        {
            if (string.IsNullOrEmpty(propertyFilter.PropsizeF))
            {
                propertyFilter.PropsizeF = "0 - 15000";
            }

            if (string.IsNullOrEmpty(propertyFilter.PropsizeM))
            {
                propertyFilter.PropsizeM = "0 - 1500";
            }

            string[] fvalues = propertyFilter.PropsizeF.Split(new string[] { "-" }, StringSplitOptions.RemoveEmptyEntries);
            propertyFilter.FloorMinF = decimal.Parse(fvalues[0]);
            propertyFilter.FloorMaxF = decimal.Parse(fvalues[1]);

            string[] mvalues = propertyFilter.PropsizeM.Split(new string[] { "-" }, StringSplitOptions.RemoveEmptyEntries);
            propertyFilter.FloorMinM = decimal.Parse(mvalues[0]);
            propertyFilter.FloorMaxM = decimal.Parse(mvalues[1]);
        }
        const int PageSize = AppConstants.PageSize;
        //PropertyFilter GetInitialValue
        public ActionResult QuickSearch(PropertyFilter propertyFilter)
        {
            return RedirectToAction("searchresult", new { Proplocation = propertyFilter.Proplocation, Proptype = propertyFilter.Proptype, Distance = propertyFilter.Distance });
        }

        public ActionResult SearchResult(PropertyFilter propertyFilter, SearchParameters parameters, FormCollection myfrm)
        {
            ViewBag.MetaTitle = "Property Search Results : Aston Rose";
            ViewBag.MetaDescription = "Property Search Results : Aston Rose";
            ViewBag.PageTitle = "Property Search Results  - ";
            ViewBag.GoogleMapKey = ConfigurationManager.AppSettings["GoogleMapsKey"];
            SplitValues(propertyFilter);


            try
            {
                if (parameters.FreeSearch != null)
                {
                    parameters.FreeSearch = parameters.FreeSearch.Replace("/", " ");
                }
                FillFacets(parameters, propertyFilter);
                
                var start = (parameters.PageIndex - 1) * parameters.PageSize;
                var sq = BuildQueryPriceRange(parameters);
                sq = MultipleFilterQry(sq, parameters, propertyFilter);
                var mySort = new[] {
                                        new SolrNet.SortOrder("score", SolrNet.Order.DESC)
									};
                var options = new QueryOptions();
                options.Rows = parameters.PageSize;
                options.Start = start;
                options.SpellCheck = new SpellCheckingParameters();
                options.Facet = new FacetParameters
                {
                    Queries = AllFacetFields.Except(SelectedFacetFields(parameters))
                                                                          .Select(f => new SolrFacetFieldQuery(f) { MinCount = 1 })
                                                                          .Cast<ISolrFacetQuery>()
                                                                          .ToList(),
                    Limit = 9999,
                };
                options.FilterQueries = BuildFilterQueries(parameters);
                string postcode = propertyFilter.Proplocation;
                postcode = SCHelpers.EmptyIfStr(postcode);
                if (postcode != "")
                {
                    if (postcode.ToLower() == "w1")
                    {
                        postcode = "London," + postcode;
                    }
                    parameters.PostCode = postcode;
                    int distance = SCHelpers.EmptyIfInt(propertyFilter.Distance);
                    parameters.Distance = distance == 0 ? 999 : distance;
                    distance = Convert.ToInt32(distance / 0.62137);
                    GeoLoc gl = GeoCoder.LocateGooglePostcode(postcode.ToString()) ?? new GeoLoc();
                    ViewBag.latitude = gl.Lat;
                    ViewBag.longitude = gl.Lon;
                    ViewBag.mapzoom = 11;
                    options.AddFilterQueries((ISolrQuery)new SolrQueryByDistance("proplocation", gl.Lat, gl.Lon, distance, CalculationAccuracy.Radius));
                    //Below query to find the nearest first
                    options.OrderBy = new[] { new SolrNet.SortOrder("geodist()", Order.ASC) };
                    options.ExtraParams = new Dictionary<string, string>
                                          {
                                              // uncomment for filtering by distance
                                              {"fq", "{!geofilt}"},
                                              {"d", distance.ToString(CultureInfo.InvariantCulture)}, // replace distance with your radius filter
                                              {"sfield", "proplocation"}, // replace lat_long with your field in solr that stores the lat long values
                                              {"pt", gl.Lat + "," + gl.Lon}, // this is the point of reference
                                          };
                                                     
                }
                else
                {
                    postcode = SCHelpers.EmptyIfStr(parameters.PostCode);
                    if (postcode != "")
                    {
                        int distance = SCHelpers.EmptyIfInt(Request["d"]);
                        parameters.Distance = distance == 0 ? 999 : distance;
                        distance = Convert.ToInt32(distance / 0.62137);

                        GeoLoc gl = GeoCoder.LocateGooglePostcode(postcode.ToString()) ?? new GeoLoc();
                        options.AddFilterQueries((ISolrQuery)new SolrQueryByDistance("proplocation", gl.Lat, gl.Lon, distance, CalculationAccuracy.Radius));
                    }
                    options.OrderBy = mySort;
                }
               
                                               
                var matchingproperties = solr.Query(sq, options);


                var currenturl = UrlHelperExtensions.UrlOriginal(Request);
                var parts = currenturl.ToString().Split('?');
                string reseturl = currenturl.ToString();
                if (parts.Count() > 0)
                {
                    reseturl = parts[0] + "?q=" + parameters.FreeSearch + "&page=1";
                }
                else
                {
                    reseturl = currenturl.ToString();
                }

                var view = new PropertyView
                {

                    SolrProperties = matchingproperties,
                    //Map = DisplayPoints(matchingproperties),
                    Search = parameters,
                    TotalCount = matchingproperties.NumFound,
                    Facets = matchingproperties.FacetFields,
                    DidYouMean = GetSpellCheckingResult(matchingproperties),
                    Filter = propertyFilter,
                    SortSelectedItem = parameters.Sort,
                    PageSizeSelectedItem = parameters.PageSize,
                    PageResetURL = reseturl,

                };

                view.TravelDistance.Add(new SelectListItem() { Text = "All", Value = "" });
                foreach (var t in SCHelpers.TravelDistanceDropdown().ToList())
                {
                    view.TravelDistance.Add(new SelectListItem() { Text = t.Text, Value = t.Value, Selected = (t.Value == parameters.Distance.ToString()) });
                }


                return View(view);

            }
            catch (InvalidFieldException)
            {
                return View(new PropertyView
                {
                    QueryError = true,
                });
            }
        }

        private void FillFacets(Models.SearchParameters parameters, Models.PropertyFilter propertyFilter)
        {

            if (!string.IsNullOrEmpty(propertyFilter.Proptype))
            {
                parameters.Facets.Add("proptype", propertyFilter.Proptype);
            }
            if (!string.IsNullOrEmpty(propertyFilter.Tenure))
            {
                parameters.Facets.Add("tenure", propertyFilter.Tenure);
            }

            if (!string.IsNullOrEmpty(propertyFilter.Category))
            {
                parameters.Facets.Add("category", propertyFilter.Category);
            }
        }


        #region Solr Query & Facets
        #region "Solor Stuffs"



        private static readonly string[] AllFacetFields = new[] { "proptype", "tenure", "category", "region", "proplocation", "propsize" };

        public ISolrQuery BuildQuery(SearchParameters parameters)
        {

AstonRoseFrondEnd/Views/Property/Detail.cshtml
@using Jmelosegui.Mvc.Controls
@using Jmelosegui.Mvc.Controls.Overlays.Markers
@using System.Globalization
@using Telerik.Web.Mvc.UI

<script type="text/javascript">
    function getPostSuccess() {

        if ($("#form1").text() == "") {
            alert('Your enquiry was submitted successfully, We will get back to you shortly.');
        }
        else {
            alert($("#form1").text());
        }


    }
    function showFaliure() {

        alert('There is an error, Please contact Aston Rose Administrator');
        alert($("form1").text());
    }
    function AddToMyProperty(ctl, itemId) {
        
        $.getJSON(
        '@(Url.Action("AddToMyProperty", "Property"))',
        { propertyId: itemId },
        function (d) {

            $("#PropCount").text(d);
            $("#" + itemId).css("display", "none");
            $("#" + itemId).next().css("display", "");
        }
    );
    }
</script>
@model AstonRoseFrondEnd.Models.PropertyListModel
@{
    var detail = Model.SelectedProperty;
    var contacts = Model.Contacts;
    var images = Model.UploadedImages;
    var enquiry = Model.Enquiry;
}
<section class="row content">
 
<div class="eight columns page-controls">
    	<ul class="pagination">
          <li class="arrow"><a href="javascript:window.history.go(-1);">&laquo; Back</a></li>
		</ul>

        @if (!string.IsNullOrEmpty(detail.PDF))
         {
            <a href="@(System.Configuration.ConfigurationManager.AppSettings["FileUploadURL"] + detail.PDF)" target="_blank" class="button radius small secondary"><i class="icon-download-alt"></i><span class="text">Download PDF</span></a>
         }
         
         @if (!string.IsNullOrEmpty(detail.EPC))
         {
            <a href="@(System.Configuration.ConfigurationManager.AppSettings["FileUploadURL"] + detail.EPC)" target="_blank" class="button radius small secondary"><i class="icon-download-alt"></i><span class="text">Download EPC</span></a>
         }
        
        @if (detail.Added)
        {
<a href="#" class="button radius small disabled">Added</a>
        }
        else
        {
<a style="display:" id="@detail.Id"  href="javascript:AddToMyProperty(this, @detail.Id)" class="button radius small">Add to my property list</a>    
<a href="#" style="display:none" class="button radius small disabled">Added</a>
        }
        
    </div>
    
    <div class="four columns">
  
    	<h1>@detail.ToString()</h1>
        <p><span class="under-offer">@detail.Status</span></p>
        
        <div class="panel radius contact">
        @foreach (var contact in contacts)
        {
            if (contact != null)
            {
        	<ul class="no-bullet">
                        	<li>Contact:</li>
                            <li><i class="icon-user"></i> @(contact.FirstName + " " + contact.LastName)</li>
                            <li><i class="icon-phone"></i> @contact.TelephoneNumber</li>
                            <li><i class="icon-envelope-alt"></i> <a href="mailto:@contact.Email?subject=@detail.ToString()">Email @contact.FirstName</a></li>
                        </ul>
            }
        }
        </div>
        
        
        <p> @Html.Raw(detail.Description)</p>

        <ul class="block-grid two-up particulars">
        	<li><h2>Type</h2>
            <p>@detail.Type</p></li>
            <li><h2>Rent</h2>
            <p>@detail.Price</p></li>
            @if (!string.IsNullOrEmpty(@detail.Tenure))
            {
            <li><h2>Tenure</h2>
            <p>@detail.Tenure</p></li>
            }
            @if (!string.IsNullOrEmpty(@detail.Incentive))
            {
            <li><h2>Incentive</h2>
            <p>@detail.Incentive</p></li>
            }
            @if (!string.IsNullOrEmpty(@detail.SquareFeet))
            {
            <li><h2>Floor Area (sq ft)</h2>
            <p>@detail.SquareFeet</p></li>
            }
            
            @if (!string.IsNullOrEmpty(@detail.SquareMeters))
            {
            <li><h2>Floor Area (sq m)</h2>
            <p>@detail.SquareMeters</p></li>
            }
        </ul>
        
    </div>
    
     <div class="four columns">
     
      <div class="tabs cf">
      	<a href="#" class="button radius small map-but"><i class="icon-map-marker"></i></a>
      	<a href="#" class="button radius small pic-but"><i class="icon-camera"></i></a>
      </div>
     
     <div class="map-panel-dets" style="display:block;visibility:hidden" >
     

        @(Html.Telerik().GoogleMap()
                .Name("map")
                .Culture(CultureInfo.CurrentCulture)
                .Width(446)
                .Height(300)
                .Latitude(detail.Latitude ?? 0)
                .Longitude(detail.Longitude ?? 0)
                .Zoom(17)
                .Markers(m => m.Add().Title(detail.ToString())
                .Latitude(detail.Latitude ?? 0)
                .Longitude(detail.Longitude ?? 0)
                .Window(window => window.Add()
                                                                    .Content(
            @<text><div>
           
            <h2 id="firstHeading" class="firstHeading" style="width:300px">
                @detail.ToString()</h2>
            
        </div>                                                                        
        </text>)
                                                                            .MaxWidth(200)
                                                                            .zIndex(3)
                                                                            .DisableAutoPan(false)
                                                            )




                        )
                        )

     </div><!-- end map-panel-dets -->
    	
      <div class="pic-panel" >
       
        <div class="lrg-image">
        @foreach (var ui in images)
        {
        	<div id="img@(ui.Id)"><img src="@AstonRoseFrondEnd.Helpers.CommonHelper.ScaleImage(ui.ImageName, 446, 300)" alt=""></div>
        }
            

        </div>
        <ul class="tbn-image cf">
        	 @foreach (var ui in images)
          {
              <li><a href="#img@(ui.Id)"><img src="@AstonRoseFrondEnd.Helpers.CommonHelper.ScaleImage(ui.ImageName, 112, 74)" alt=""></a></li>
          }
           
        </ul>
        </div><!-- end pic-panel -->
        
        <div class="row quick-enquiry">
        
       @using (Ajax.BeginForm("SendDetailEnquiry", "Property", new AjaxOptions
       {
           //   OnBegin="validateForm",

           UpdateTargetId = "form1",
           InsertionMode = InsertionMode.InsertAfter,
           OnSuccess = "getPostSuccess",
           OnFailure = "showFaliure"
       }))
       {
            <div style="display:none" id="form1"></div>
     <div class="eight columns">
        <h2>Quick Enquiry</h2>
        </div>
        
        	<div class="four columns">
            <label for="">Name</label>
            @Html.Hidden("Enquiry.Id", Model.SelectedProperty.Id)
            @Html.EditorFor(model => model.Enquiry.Name)
            @Html.ValidationMessageFor(model => model.Enquiry.Name)
            <label for="">Email</label>
            @Html.EditorFor(model => model.Enquiry.Email)
            @Html.ValidationMessageFor(model => model.Enquiry.Email)
             <label for="">Tel</label>
            @Html.EditorFor(model => model.Enquiry.Tel)
            @Html.ValidationMessageFor(model => model.Enquiry.Tel)
            </div>
            
            <div class="four columns">
             <label for="">Message</label>
            @Html.TextAreaFor(model => model.Enquiry.Message, new { style="height:150px"})
            </div>
            
            <div class="eight columns">
            <input type="submit" class="button radius small" value="Send">
            </div>
       }
        @*<script type="text/javascript">
            function validateForm() {
                return $('form0').validate().form();
            } 
            
        </script>*@ 
        	
        
        </div>
    
    </div>
   </section>
   <script src="@Url.Content("~/Scripts/javascripts/foundation.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/javascripts/jquery.ui.touch-punch.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/javascripts/app.js")" type="text/javascript"></script>

<script>

    $(function () {
        setTimeout(function () {
            $(".map-panel-dets").css("display", "none");
            $(".map-panel-dets").css("visibility", "visible");

        }, 1000);
    });
</script>

AstonRoseFrondEnd/Views/Property/Index.cshtml
@{
    ViewBag.CurrentPage = "Index";
}
<section class="row content">
  
  	<div class="eight columns masthead">
  		<h1>Property Search</h1>
    </div>
    
    <div class="refine-panel cf">
    
    @{Html.RenderPartial("_Filters");} 
    
    </div>
  


  </section>
<!-- end row -->

AstonRoseFrondEnd/Views/Property/MyProperties.cshtml
@model AstonRoseFrondEnd.Models.MyProperty
<script type="text/javascript">
    function getPostSuccess() {

        if ($("#form1").text() == "") {
            alert('Your enquiry was submitted successfully, We will get back to you shortly.');
        }
        else {
            alert($("#form1").text());
        }


    }
    function showFaliure() {

        alert('There is an error, Please contact Aston Rose Administrator');
        alert($("form1").text());
    }
    function loadpage(pageIndex) {
        window.location.href = '@Url.Content("~/Property/MyProperties")' + '?pageIndex=' + pageIndex.toString();
    }
</script>
<section class="row content">
  
  	<div class="eight columns masthead">
  		<h1>My Property List</h1>
    </div>
    
    <div class="eight columns page-controls">
    	@{Html.RenderPartial("_Pagination",Model.Pagination);}

    </div>
    
 	<ul class="block-grid two-up prop-thumbs">
    @foreach (var p in Model.MyProperties)
    {
      <li>
      	<h1><a href="@Url.Action("detail", new { name = AstonRoseFrondEnd.Helpers.CommonHelper.GetSeoTitle(p.ToString()), Id = p.Id })">@p.ToString()</a></h1>
        	<div class="row">
            	<div class="four columns thumbnail"><a href="@Url.Action("detail", new { name = AstonRoseFrondEnd.Helpers.CommonHelper.GetSeoTitle(p.ToString()), Id = p.Id })"><img src="@AstonRoseFrondEnd.Helpers.CommonHelper.ScaleImage(p.Image, 216, 162)" alt=""></a><span class="under-offer">@p.Status</span></div>
                <div class="four columns propertylist">
                	<p><span>Type:</span> @p.Type<br/>
<span>Tenure:</span> @p.Tenure<br/>
<span>Price:</span> @p.Price<br/>
@if (!string.IsNullOrEmpty(p.Incentive))
{
<span>Incentive:</span> @p.Incentive
}</p>
    
<a href="@Url.Action("remove", new { propertyId = p.Id })" class="button radius small"><i class="icon-trash"></i>Remove</a>
                </div>
            </div><!-- end row -->
      </li>
    }
	</ul>
  

  <div class="eight columns page-controls">
    	@{Html.RenderPartial("_Pagination",Model.Pagination);}
    </div>
  
 <div class="row quick-enquiry">
        @using (Ajax.BeginForm("SendEnquiry", "Property", new AjaxOptions
        {
            //   OnBegin="validateForm",
             
            UpdateTargetId = "form1",
            InsertionMode = InsertionMode.InsertAfter,
            OnSuccess = "getPostSuccess",
            OnFailure = "showFaliure"
        }))
        {
            <div style="display:none" id="form1"></div>
     <div class="eight columns">
        <h2>Quick Enquiry</h2>
        </div>
        
        	<div class="four columns">
            <label for="">Name</label>
            @Html.EditorFor(model => model.Enquiry.Name)
            @Html.ValidationMessageFor(model => model.Enquiry.Name)
            <label for="">Email</label>
            @Html.EditorFor(model => model.Enquiry.Email)
            @Html.ValidationMessageFor(model => model.Enquiry.Email)
             <label for="">Tel</label>
            @Html.EditorFor(model => model.Enquiry.Tel)
            @Html.ValidationMessageFor(model => model.Enquiry.Tel)
            </div>
            
            <div class="four columns">
             <label for="">Message</label>
            @Html.TextAreaFor(model => model.Enquiry.Message, new { style="height:150px"})
            </div>
            
            <div class="eight columns">
            <input type="submit" class="button radius small" value="Send">
            </div>
        }
        <script type="text/javascript">
            function validateForm() {
                return $('form0').validate().form();
            } 
            
        </script>
       
        
        </div>

  </section>
<!-- end row -->

AstonRoseFrondEnd/Views/Property/Search.cshtml
@using AstonRoseFrondEnd.Helpers;
@using AstonRoseFrondEnd.Models;
{
    ViewBag.Title = "Job Search";
}
<section class="row content">
  
  	<div class="eight columns masthead">
  		<h1>Property Search</h1>
    </div>
    
    <div class="refine-panel cf">
    
    @{Html.RenderPartial("_Filters");} 
    
    </div>
  


  </section>
<!-- end row -->

AstonRoseFrondEnd/Views/Property/_marker.cshtml
@using Jmelosegui.Mvc.Controls
@using System.Globalization
@using Telerik.Web.Mvc.UI
@model AstonRoseFrondEnd.Models.Property

@Model.BuildingName